#!/usr/bin/env node
/**
 * Generate sitemap.xml for SEO
 * This script runs after static export to generate sitemap with correct URLs
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Configuration
const SITE_URL = process.env.SITE_URL || 'https://lessup.github.io/graph-viewer';
const OUTPUT_DIR = process.env.OUTPUT_DIR || path.join(__dirname, '../out');

// Static pages to include
const staticPages = [
  { path: '/', priority: '1.0', changefreq: 'weekly' },
  { path: '/editor/', priority: '0.9', changefreq: 'weekly' },
];

// Documentation pages
const docsPages = [{ path: '/docs/', priority: '0.8', changefreq: 'monthly' }];

/**
 * Generate ISO date string
 */
function getISODate() {
  return new Date().toISOString();
}

/**
 * Escape special XML characters
 */
function escapeXml(unsafe) {
  return unsafe.replace(/[<>&'"]/g, (c) => {
    switch (c) {
      case '<': return '&lt;';
      case '>': return '&gt;';
      case '&': return '&amp;';
      case '"': return '&quot;';
      case "'": return '&apos;';
    }
    return c;
  });
}

/**
 * Generate sitemap XML
 */
function generateSitemap() {
  const lastmod = getISODate();
  
  const allPages = [...staticPages, ...docsPages];
  
  let sitemap = '<?xml version="1.0" encoding="UTF-8"?>\n';
  sitemap += '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n';
  sitemap += '  <!-- Generated by generate-sitemap.mjs -->\n';
  sitemap += `  <!-- Last generated: ${lastmod} -->\n\n`;
  
  for (const page of allPages) {
    const url = `${SITE_URL}${page.path}`;
    sitemap += '  <url>\n';
    sitemap += `    <loc>${escapeXml(url)}</loc>\n`;
    sitemap += `    <lastmod>${lastmod}</lastmod>\n`;
    sitemap += `    <changefreq>${page.changefreq}</changefreq>\n`;
    sitemap += `    <priority>${page.priority}</priority>\n`;
    sitemap += '  </url>\n';
  }
  
  sitemap += '</urlset>\n';
  
  return sitemap;
}

/**
 * Main function
 */
async function main() {
  try {
    console.log('🔍 Generating sitemap...');
    console.log(`   Site URL: ${SITE_URL}`);
    console.log(`   Output: ${OUTPUT_DIR}`);
    
    // Generate sitemap content
    const sitemap = generateSitemap();
    
    // Ensure output directory exists
    if (!fs.existsSync(OUTPUT_DIR)) {
      console.log(`   Creating output directory: ${OUTPUT_DIR}`);
      fs.mkdirSync(OUTPUT_DIR, { recursive: true });
    }
    
    // Write sitemap
    const sitemapPath = path.join(OUTPUT_DIR, 'sitemap.xml');
    fs.writeFileSync(sitemapPath, sitemap, 'utf8');
    
    // Calculate stats
    const stats = fs.statSync(sitemapPath);
    const sizeKB = (stats.size / 1024).toFixed(2);
    const urlCount = (sitemap.match(/<url>/g) || []).length;
    
    console.log('');
    console.log('✅ Sitemap generated successfully!');
    console.log(`   File: ${sitemapPath}`);
    console.log(`   Size: ${sizeKB} KB`);
    console.log(`   URLs: ${urlCount}`);
    console.log('');
    console.log('ℹ️  Make sure to update robots.txt if the sitemap location changes');
    console.log('   Current location: /sitemap.xml');
    
  } catch (error) {
    console.error('❌ Error generating sitemap:', error.message);
    process.exit(1);
  }
}

// Run if called directly
if (import.meta.url === `file://${process.argv[1]}`) {
  main();
}

export { generateSitemap };
